CREATE DATABASE Company 
USE Company
DROP DATABASE Company


CREATE TABLE EMPLOYEE (
SSN INT PRIMARY KEY  , 
BirthDate DATETIME ,
Fname VARCHAR(50) ,
Lname VARCHAR(50) , 
Gender CHAR CHECK  (Gender = 'F' OR Gender = 'M'),   -- F For Female && M For Male 
);

ALTER TABLE EMPLOYEE ADD M_SSN INT FOREIGN KEY REFERENCES EMPLOYEE(SSN) ;


ALTER TABLE EMPLOYEE
ADD E_DNUM INT FOREIGN KEY REFERENCES DEPARTMENT(DNUM) ;


SELECT * FROM EMPLOYEE ;




CREATE TABLE DEPARTMENT (
DNUM INT PRIMARY KEY IDENTITY(1 , 1 ), 
DName VARCHAR(50) ,

) ;
ALTER TABLE DEPARTMENT ADD ManagerSSN INT FOREIGN KEY REFERENCES EMPLOYEE(SSN) ;
ALTER TABLE DEPARTMENT ADD HiringDate DATETIME ;
SELECT * FROM DEPARTMENT ;


CREATE TABLE Dept_Locatioins(
Dept_Num INT FOREIGN KEY REFERENCES  DEPARTMENT(DNUM) ,
LOCATION VARCHAR(255) ,
PRIMARY KEY (LOCATION , Dept_Num) 
);
SELECT * FROM Dept_Locatioins ;



CREATE TABLE PROJECT (
PNUM INT PRIMARY KEY IDENTITY(1 , 1 ), 
Pname VARCHAR(255) ,
City VARCHAR(255)  ,
LOCATION VARCHAR(255) 

);
ALTER TABLE  PROJECT ADD DNum INT FOREIGN KEY REFERENCES DEPARTMENT(DNUM) ;


SELECT * FROM PROJECT ;
CREATE TABLE DEPENDENT (
DeName VARCHAR (255) ,
EMP_SSN INT FOREIGN KEY REFERENCES EMPLOYEE(SSN) ,
Gender CHAR(1) CHECK  (Gender = 'F' OR Gender = 'M'),   -- F For Female && M For Male 
BirthDate DATETIME  , 
PRIMARY KEY (EMP_SSN , DeName)  -- Composite primary key

);

SELECT * FROM DEPENDENT ;

CREATE TABLE EMPLOYEE_PROJECT (
EMP_SSN INT FOREIGN KEY REFERENCES EMPLOYEE(SSN) ,
P_NUM INT FOREIGN KEY REFERENCES PROJECT(PNUM) ,
PRIMARY KEY(EMP_SSN , P_NUM) , --composite PK
Hours INT 
);
SELECT * FROM EMPLOYEE_PROJECT ;










